import WorkflowLog from "@/modules/automation/schemas/WorkflowLog";
import dbConnect from "@/lib/db";
import Task from "@/modules/tasks/schemas/Task";

class MockQueue {
  name: string;
  constructor(name: string) {
    this.name = name;
  }
  async add(name: string, data: any) {
    console.log(`[MockQueue] Added job ${name} to ${this.name}`);
    // Process inline for the prototype to avoid needing a real Redis server
    if (this.name === "executionQueue") {
       setTimeout(() => processExecutionJob({ data }), 100);
    }
    return { id: Date.now().toString() };
  }
}

export const emailQueue = new MockQueue("emailQueue") as any;
export const executionQueue = new MockQueue("executionQueue") as any;

// Mock workers
export const emailWorker = { on: () => {} } as any;
export const executionWorker = { on: () => {} } as any;

async function processExecutionJob(job: any) {
    await dbConnect();
    const { action, logId, triggerName, workflowId, companyId, targetId } = job.data;
    
    console.log(`[BullMQ Mock] Executing workflow action: ${action.type}`);
    
    let actionSuccess = true;
    let actionDetails = "Action executed successfully.";

    try {
      if (action.type === "Create Task") {
        await Task.create({
          companyId,
          title: action.payload.title || `Automated Task for ${triggerName}`,
          description: action.payload.description || `Generated by Workflow`,
          status: "To Do",
          dueDate: new Date(Date.now() + 86400000) // Default +1 day
        });
      } else if (action.type === "Send Email") {
        console.log(`[Workflow Engine] Email sent to ${action.payload.to} with subject: ${action.payload.subject}`);
      } else if (action.type === "Assign User") {
        const { userId } = action.payload;
        if (!userId) throw new Error("No User ID provided for assignment.");
        if (triggerName.includes("Lead")) {
          const Lead = require('@/modules/leads/schemas/Lead').default;
          await Lead.findByIdAndUpdate(targetId, { assignedUserId: userId });
        } else if (triggerName.includes("Project")) {
          const Project = require('@/modules/projects/schemas/Project').default;
          await Project.findByIdAndUpdate(targetId, { assignedUserId: userId });
        }
      }
    } catch (err: any) {
      actionSuccess = false;
      actionDetails = `Action ${action.type} failed: ${err.message}`;
    }

    if (logId) {
      await WorkflowLog.findByIdAndUpdate(logId, { 
        status: actionSuccess ? "success" : "error",
        details: actionDetails
      });
    }
}
