import WorkflowLog from "@/modules/automation/schemas/WorkflowLog";
import dbConnect from "@/lib/db";
import Task from "@/modules/tasks/schemas/Task";

class MockQueue {
  name: string;
  constructor(name: string) {
    this.name = name;
  }
  async add(name: string, data: any) {
    console.log(`[MockQueue] Added job ${name} to ${this.name}`);
    if (this.name === "executionQueue") {
       setTimeout(() => processExecutionJob({ data }), 100);
    } else if (this.name === "emailQueue") {
       setTimeout(() => processEmailJob({ data }), 100);
    }
    return { id: Date.now().toString() };
  }
}

async function processEmailJob(job: any) {
  const { to, subject, html, campaignId } = job.data;
  console.log(`[EmailWorker] Sending email to ${to} for campaign ${campaignId}`);

  const nodemailer = require('nodemailer');
  
  // We use streamTransport to mock sending in dev mode without needing real SMTP credentials
  const transporter = nodemailer.createTransport({
    streamTransport: true,
    newline: 'windows'
  });

  try {
    await transporter.sendMail({
      from: '"CRM Marketing" <no-reply@crmos.com>',
      to,
      subject,
      html
    });

    if (campaignId) {
      await dbConnect();
      const EmailCampaign = require('@/modules/marketing/schemas/EmailCampaign').default;
      await EmailCampaign.updateOne({ _id: campaignId }, { $inc: { totalSent: 1 } });
    }
    console.log(`[EmailWorker] Successfully sent email to ${to}`);
  } catch (err: any) {
    console.error(`[EmailWorker] Failed to send email to ${to}: ${err.message}`);
  }
}

export const emailQueue = new MockQueue("emailQueue") as any;
export const executionQueue = new MockQueue("executionQueue") as any;

// Mock workers
export const emailWorker = { on: () => {} } as any;
export const executionWorker = { on: () => {} } as any;

async function processExecutionJob(job: any) {
    await dbConnect();
    const { action, logId, triggerName, workflowId, companyId, targetId } = job.data;
    
    console.log(`[BullMQ Mock] Executing workflow action: ${action.type}`);
    
    let actionSuccess = true;
    let actionDetails = "Action executed successfully.";

    try {
      if (action.type === "Create Task") {
        await Task.create({
          companyId,
          title: action.payload.title || `Automated Task for ${triggerName}`,
          description: action.payload.description || `Generated by Workflow`,
          status: "To Do",
          dueDate: new Date(Date.now() + 86400000) // Default +1 day
        });
      } else if (action.type === "Send Email") {
        let { to, subject, body } = action.payload;
        if (!to) to = job.data.payload.email;
        if (to) {
          const { sendGmail } = await import('@/lib/googleClient');
          const userId = job.data.payload.assignedTo || job.data.payload.createdBy || job.data.payload.assignedUserId;
          if (userId) {
            await sendGmail(userId.toString(), companyId.toString(), to, subject || 'Automated Email', body || 'Hello');
            actionDetails = `Email sent successfully to ${to}`;
          } else {
             throw new Error('Cannot send email via workflow: No userId found in payload to use for OAuth.');
          }
        } else {
          throw new Error('No destination email found.');
        }
      } else if (action.type === "Assign User") {
        const { userId } = action.payload;
        if (!userId) throw new Error("No User ID provided for assignment.");
        if (triggerName.includes("Lead")) {
          const Lead = require('@/modules/leads/schemas/Lead').default;
          await Lead.findByIdAndUpdate(targetId, { assignedUserId: userId });
        } else if (triggerName.includes("Project")) {
          const Project = require('@/modules/projects/schemas/Project').default;
          await Project.findByIdAndUpdate(targetId, { assignedUserId: userId });
        }
      } else if (action.type === "Trigger Webhook") {
        const { url, method, authHeader } = action.payload;
        if (!url) throw new Error("No URL provided for webhook.");
        
        const headers: Record<string, string> = {
          "Content-Type": "application/json"
        };
        if (authHeader) {
          headers["Authorization"] = authHeader;
        }

        const fetchOptions: RequestInit = {
          method: method || "POST",
          headers
        };
        
        // Pass the triggering event's payload to the external service
        if (fetchOptions.method !== "GET") {
          fetchOptions.body = JSON.stringify(job.data.payload);
        }

        const response = await fetch(url, fetchOptions);
        if (!response.ok) {
          throw new Error(`Webhook responded with status ${response.status}`);
        }
        
        actionDetails = `Webhook triggered successfully. Status: ${response.status}`;
      } else if (action.type === "Send SMS / WhatsApp" || action.type === "Send SMS") {
        let { to, body } = action.payload;
        
        if (!to) {
          // Fallback to payload phone
          to = job.data.payload.phone || job.data.payload.whatsAppNumber || job.data.payload.whatsappNumber;
        }
        
        if (!to) throw new Error("No destination phone number found.");

        const { sendTwilioSMS } = await import('@/lib/twilioClient');
        const twilioRes = await sendTwilioSMS(to, body, companyId.toString());
        
        if (!twilioRes.success) {
          throw new Error(twilioRes.error || "Twilio error");
        }

        actionDetails = `Message sent successfully to ${to}. Twilio SID: ${twilioRes.messageId}`;
      }
    } catch (err: any) {
      actionSuccess = false;
      actionDetails = `Action ${action.type} failed: ${err.message}`;
    }

    if (logId) {
      await WorkflowLog.findByIdAndUpdate(logId, { 
        status: actionSuccess ? "success" : "error",
        details: actionDetails
      });
    }
}
