import mongoose from "mongoose";
import Workflow from "../schemas/Workflow";
import WorkflowLog from "../schemas/WorkflowLog";
import Task from "@/modules/tasks/schemas/Task";

export async function evaluateWorkflows(companyId: string, triggerName: string, targetId: string, payload: any) {
  try {
    // Find all active workflows for this company and trigger
    const workflows = await Workflow.find({
      companyId: new mongoose.Types.ObjectId(companyId),
      trigger: triggerName,
      active: true
    });

    if (!workflows.length) return;

    for (const workflow of workflows) {
      let conditionsMet = true;

      // Evaluate Conditions
      for (const condition of workflow.conditions) {
        const payloadValue = payload[condition.field];
        
        // If field is completely missing, condition fails
        if (payloadValue === undefined) {
          conditionsMet = false;
          break;
        }

        switch (condition.operator) {
          case "equals":
            if (String(payloadValue) !== String(condition.value)) conditionsMet = false;
            break;
          case "not_equals":
            if (String(payloadValue) === String(condition.value)) conditionsMet = false;
            break;
          case "greater_than":
            if (Number(payloadValue) <= Number(condition.value)) conditionsMet = false;
            break;
          case "less_than":
            if (Number(payloadValue) >= Number(condition.value)) conditionsMet = false;
            break;
          case "contains":
            if (!String(payloadValue).toLowerCase().includes(String(condition.value).toLowerCase())) conditionsMet = false;
            break;
        }

        if (!conditionsMet) break; // Optimization: fail fast
      }

      if (conditionsMet) {
        // Execute Actions
        let actionSuccess = true;
        let actionDetails = "Actions executed successfully.";

        for (const action of workflow.actions) {
          try {
            if (action.type === "Create Task") {
              await Task.create({
                companyId: workflow.companyId,
                title: action.payload.title || `Automated Task for ${triggerName}`,
                description: action.payload.description || `Generated by Workflow: ${workflow.title}`,
                status: "To Do",
                dueDate: new Date(Date.now() + 86400000) // Default +1 day
              });
            } else if (action.type === "Send Email") {
              // Stub: In a real app, call email service
              console.log(`[Workflow Engine] Email sent to ${action.payload.to} with subject: ${action.payload.subject}`);
            }
          } catch (err: any) {
            actionSuccess = false;
            actionDetails = `Action ${action.type} failed: ${err.message}`;
            break;
          }
        }

        // Log the execution
        await WorkflowLog.create({
          companyId: workflow.companyId,
          workflowId: workflow._id,
          trigger: triggerName,
          targetId: String(targetId),
          status: actionSuccess ? "success" : "error",
          details: actionDetails
        });
      }
    }
  } catch (error) {
    console.error("[Workflow Engine] Error evaluating workflows:", error);
  }
}
